In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"C:\Users\Harujah\Desktop\Pantech_Courses\ML\ML_Projects\datasets\exam_marks.csv"
df = pd.read_csv(path)
df

hours  age  internet  marks
0     6.83   15         1  78.50
1     6.56   16         0  76.74
2      NaN   17         1  78.68
3     5.67   18         0  71.82
4     8.67   19         1  84.19
..     ...  ...       ...    ...
196   8.56   19         1  84.68
197   8.94   20         1  86.75
198   6.60   15         1  78.05
199   8.35   16         1  83.50
200   4.15   15         0  81.45

[201 rows x 4 columns]

In [3]:
df.columns[df.isna().any()]

Index(['hours'], dtype='object')

In [4]:
df.hours = df.hours.fillna(df.hours.mean())
df

hours  age  internet  marks
0     6.830000   15         1  78.50
1     6.560000   16         0  76.74
2    30.276378   17         1  78.68
3     5.670000   18         0  71.82
4     8.670000   19         1  84.19
..         ...  ...       ...    ...
196   8.560000   19         1  84.68
197   8.940000   20         1  86.75
198   6.600000   15         1  78.05
199   8.350000   16         1  83.50
200   4.150000   15         0  81.45

[201 rows x 4 columns]

In [6]:
X = df.iloc[:, :-1].values
X

array([[6.83000000e+00, 1.50000000e+01, 1.00000000e+00],
       [6.56000000e+00, 1.60000000e+01, 0.00000000e+00],
       [3.02763776e+01, 1.70000000e+01, 1.00000000e+00],
       [5.67000000e+00, 1.80000000e+01, 0.00000000e+00],
       [8.67000000e+00, 1.90000000e+01, 1.00000000e+00],
       [7.55000000e+00, 2.00000000e+01, 0.00000000e+00],
       [6.67000000e+00, 1.50000000e+01, 0.00000000e+00],
       [8.99000000e+00, 1.60000000e+01, 0.00000000e+00],
       [4.57100000e+03, 1.70000000e+01, 1.00000000e+00],
       [6.75000000e+00, 1.80000000e+01, 0.00000000e+00],
       [6.59000000e+00, 1.90000000e+01, 0.00000000e+00],
       [8.56000000e+00, 2.00000000e+01, 1.00000000e+00],
       [7.75000000e+00, 1.50000000e+01, 0.00000000e+00],
       [7.90000000e+00, 1.60000000e+01, 1.00000000e+00],
       [8.19000000e+00, 1.70000000e+01, 0.00000000e+00],
       [6.55000000e+00, 1.80000000e+01, 1.00000000e+00],
       [6.36000000e+00, 1.90000000e+01, 0.00000000e+00],
       [8.44000000e+00, 2.00000

In [7]:
Y = df.iloc[:, -1].values
Y

array([78.5 , 76.74, 78.68, 71.82, 84.19, 81.18, 76.99, 85.46, 70.66,
       77.82, 75.37, 83.88, 79.5 , 80.76, 83.08, 76.03, 76.04, 85.11,
       82.5 , 80.58, 82.18, 83.36, 70.67, 75.02, 70.96, 83.33, 74.75,
       75.65, 74.15, 80.17, 82.27, 76.14, 71.1 , 84.35, 83.08, 76.76,
       81.24, 78.21, 73.08, 83.23, 70.27, 86.41, 71.1 , 82.84, 82.38,
       72.96, 77.46, 70.11, 72.38, 71.41, 72.22, 77.77, 84.44, 71.45,
       82.21, 85.48, 75.03, 86.65, 70.9 , 71.7 , 73.61, 79.41, 76.19,
       80.43, 85.78, 70.06, 81.25, 81.7 , 69.27, 82.79, 71.8 , 71.79,
       74.97, 78.61, 77.59, 72.33, 72.08, 77.33, 70.05, 73.34, 84.  ,
       82.93, 76.63, 75.36, 77.29, 72.87, 73.4 , 81.74, 71.85, 84.6 ,
       79.56, 82.1 , 72.08, 79.1 , 81.01, 76.48, 75.39, 68.57, 83.64,
       82.3 , 75.18, 82.03, 82.99, 79.26, 77.55, 77.07, 72.1 , 73.25,
       74.25, 70.58, 81.08, 75.04, 76.38, 80.86, 78.42, 74.44, 70.34,
       85.04, 73.61, 75.55, 76.2 , 82.69, 76.83, 79.53, 83.57, 85.95,
       76.02, 77.65,

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,Y, test_size=0.25, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 2.87161513e-01  9.11649480e-01  8.86405260e-01]
 [-5.87764667e-01  9.11649480e-01  8.86405260e-01]
 [-5.92807469e-01 -8.04845357e-01  8.86405260e-01]
 [ 3.57760744e-01  1.48381443e+00 -1.12815215e+00]
 [-5.29772442e-01 -1.37701030e+00 -1.12815215e+00]
 [ 1.45963052e-01 -1.37701030e+00  8.86405260e-01]
 [ 3.75428047e-02  9.11649480e-01  8.86405260e-01]
 [-5.72636260e-01  9.11649480e-01  8.86405260e-01]
 [-4.54130409e-01 -2.32680411e-01  8.86405260e-01]
 [-5.77679062e-01  1.48381443e+00  8.86405260e-01]
 [ 5.72995311e+00 -1.37701030e+00  8.86405260e-01]
 [-5.04558431e-01 -8.04845357e-01  8.86405260e-01]
 [ 2.99786014e-02 -8.04845357e-01  8.86405260e-01]
 [-5.82721865e-01  3.39484534e-01 -1.12815215e+00]
 [-5.32293843e-01 -2.32680411e-01  8.86405260e-01]
 [ 3.04811321e-01 -1.37701030e+00 -1.12815215e+00]
 [-2.01990299e-01 -8.04845357e-01 -1.12815215e+00]
 [-6.07918380e-02  3.39484534e-01  8.86405260e-01]
 [-4.21352195e-01 -2.32680411e-01 -1.12815215e+00]
 [ 2.64468903e-01 -8.04845357e-

In [16]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [17]:
a = [[5.67,18,0]]
PredictedResults = model.predict(a)
print(PredictedResults)

[77.84055196]
